#!/usr/bin/env bash
# Loop the per-variant pipeline over every entry in catalog.json.
#
# Smallest-first ordering keeps the long-tail 5B variants from blocking
# the cheap ones, and per-variant build.log + metadata.json snapshot lets
# the orchestrator tolerate (and continue past) partial failures.
#
# Skip stages with the SKIP_STAGES env var, e.g.:
#   SKIP_STAGES=qnn_convert,coreml_convert ./run_all.sh
#
# Restrict to a subset with VARIANTS:
#   VARIANTS="pretrain:0.1b pose:0.4b" ./run_all.sh

set -eo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="${CATALOG:-/mnt/disks/zeticai_database/models/sapiens2/catalog.json}"
RESULTS_MD="${RESULTS_MD:-/mnt/disks/zeticai_database/models/sapiens2/RESULTS.md}"
SKIP_STAGES="${SKIP_STAGES:-}"

# Build the (task, size, weight_bytes) list and sort by size ascending.
mapfile -t VARIANT_LINES < <(
  python3 - <<PY
import json
from pathlib import Path
catalog = json.loads(Path('${CATALOG}').read_text())
selection = "${VARIANTS:-}".strip()
allow = set(selection.split()) if selection else None
entries = []
for v in catalog:
    if 'error' in v:
        continue
    key = f"{v['task']}:{v['size']}"
    if allow and key not in allow:
        continue
    entries.append((v.get('weights_bytes', 0), v['task'], v['size']))
entries.sort()
for sz, t, s in entries:
    print(f"{t}\t{s}\t{sz}")
PY
)

echo "[run_all] processing ${#VARIANT_LINES[@]} variants (smallest first)"
echo "[run_all] skip_stages='${SKIP_STAGES}'"

: > "$RESULTS_MD.tmp"
{
  echo "# sapiens2 build results"
  echo
  echo "Generated by \`runner/run_all.sh\`."
  echo
  echo "| variant | weights | torch_export | onnx_export | qnn (fp32+fp16) | coreml | total time |"
  echo "|---|---|---|---|---|---|---|"
} >> "$RESULTS_MD.tmp"

for line in "${VARIANT_LINES[@]}"; do
  task=$(awk '{print $1}' <<<"$line")
  size=$(awk '{print $2}' <<<"$line")
  bytes=$(awk '{print $3}' <<<"$line")
  gb=$(python3 -c "print(f'{${bytes}/1e9:.2f}')")
  out_dir="/mnt/disks/zeticai_database/models/sapiens2/${task}_$(echo "$size" | tr '.' '_')"
  log="$out_dir/build.log"
  mkdir -p "$out_dir"

  echo
  echo "==================================================================="
  echo "[run_all] $task-$size  (${gb} GB)  -> $out_dir"
  echo "==================================================================="
  start=$(date +%s)
  status=ok
  HF_HUB_DISABLE_TELEMETRY=1 python3 "$REPO_ROOT/runner/build_variant.py" \
      --task "$task" --size "$size" --skip "$SKIP_STAGES" >"$log" 2>&1 \
      || status=fail
  elapsed=$(( $(date +%s) - start ))

  python3 - <<PY >> "$RESULTS_MD.tmp"
import json
from pathlib import Path
md = Path('${out_dir}/metadata.json')
data = json.loads(md.read_text()) if md.exists() else {}
stages = data.get('stages', {})
def cell(name):
    s = stages.get(name)
    if not s: return '·'
    if s.get('status') == 'ok':   return '✅'
    if s.get('status') == 'skipped': return '—'
    if s.get('status') == 'fail': return '❌'
    return s.get('status', '?')
print(
    f"| ${task}-${size} | ${gb} GB | "
    f"{cell('torch_export')} | {cell('onnx_export')} | "
    f"{cell('qnn_convert')} | {cell('coreml_convert')} | ${elapsed}s |"
)
PY

  echo "[run_all] $task-$size finished in ${elapsed}s status=$status (log: $log)"
done

mv "$RESULTS_MD.tmp" "$RESULTS_MD"
echo "[run_all] wrote $RESULTS_MD"
