#!/usr/bin/env bash
# Run runner/test_e2e.py on every catalog variant that has model.pt2.
#
# Outputs:
#   * per-variant ``stages.verify_*`` records in metadata.json
#   * a top-level VERIFY.md table summarising max|Δ| for each backend.
#
# By default skips the QNN CPU backend check (slowest at ViT scale).
# Pass --with-qnn to include it.

set -eo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="${ROOT:-/mnt/disks/zeticai_database/models/sapiens2}"
OUT="${OUT:-$ROOT/VERIFY.md}"
WITH_QNN=""
[ "${1:-}" = "--with-qnn" ] && WITH_QNN=1

mapfile -t DIRS < <(find "$ROOT" -mindepth 1 -maxdepth 1 -type d -name "*_*" | sort)

{
  echo "# sapiens2 numerical-parity report"
  echo
  printf "Generated by \`verify_all.sh\` on %s.\n\n" "$(date -u +%FT%TZ)"
  echo "| variant | pt2 max│Δ│ | ORT max│Δ│ | QNN-CPU max│Δ│ |"
  echo "|---|---|---|---|"
} > "$OUT.tmp"

for d in "${DIRS[@]}"; do
  name=$(basename "$d")
  [ -f "$d/model.pt2" ] || { echo "[skip] $name (no model.pt2)"; continue; }
  echo "[verify] $name"
  args=("--variant-dir" "$d")
  [ -z "$WITH_QNN" ] && args+=("--skip-qnn")
  python3 "$REPO_ROOT/runner/test_e2e.py" "${args[@]}" >"$d/verify.log" 2>&1 || true

  python3 - <<PY >> "$OUT.tmp"
import json
from pathlib import Path
md = Path("$d/metadata.json")
data = json.loads(md.read_text()) if md.exists() else {}
s = data.get("stages", {})
def cell(key):
    r = s.get(key)
    if not r:
        return "·"
    if r.get("status") == "skipped":
        return "—"
    if r.get("status") == "ok":
        return f"{r.get('max_abs_diff', 0):.2e}"
    return f"❌{r.get('max_abs_diff', 0):.2e}"
print(f"| {Path('$d').name} | {cell('verify_pt2')} | {cell('verify_onnx')} | {cell('verify_qnn_cpu')} |")
PY
done

mv "$OUT.tmp" "$OUT"
echo "[verify] wrote $OUT"
