#!/usr/bin/env bash
# Run runner/test_e2e.py on every catalog variant that has model.pt2.
#
# Outputs:
#   * per-variant ``stages.verify_*`` records in metadata.json
#   * a top-level VERIFY.md table summarising max|Δ| for each backend.
#
# By default skips the QNN CPU backend check (slowest at ViT scale).
# Pass --with-qnn to include it.

set -eo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="${ROOT:-/mnt/disks/zeticai_database/models/sapiens2}"
OUT="${OUT:-$ROOT/VERIFY.md}"
WITH_QNN=""
[ "${1:-}" = "--with-qnn" ] && WITH_QNN=1

mapfile -t DIRS < <(find "$ROOT" -mindepth 1 -maxdepth 1 -type d -name "*_*" | sort)

{
  echo "# sapiens2 numerical-parity report"
  echo
  printf "Generated by \`verify_all.sh\` on %s.\n\n" "$(date -u +%FT%TZ)"
  echo "| variant | output range | pt2 rel | ORT rel | QNN-CPU rel |"
  echo "|---|---|---|---|---|"
} > "$OUT.tmp"

for d in "${DIRS[@]}"; do
  name=$(basename "$d")
  [ -f "$d/model.pt2" ] || { echo "[skip] $name (no model.pt2)"; continue; }
  echo "[verify] $name"
  args=("--variant-dir" "$d")
  [ -z "$WITH_QNN" ] && args+=("--skip-qnn")
  python3 "$REPO_ROOT/runner/test_e2e.py" "${args[@]}" >"$d/verify.log" 2>&1 || true

  python3 - <<PY >> "$OUT.tmp"
import json
import numpy as np
from pathlib import Path
md = Path("$d/metadata.json")
data = json.loads(md.read_text()) if md.exists() else {}
s = data.get("stages", {})
d = Path("$d")
out_range = "—"
ref_paths = [d / "sample_output.npy"] if (d / "sample_output.npy").exists() \
    else sorted(d.glob("sample_output_*.npy"))
if ref_paths:
    arrs = [np.load(p) for p in ref_paths]
    lo = min(float(a.min()) for a in arrs)
    hi = max(float(a.max()) for a in arrs)
    out_range = f"[{lo:+.1f}, {hi:+.1f}]"
def cell(key):
    r = s.get(key)
    if not r:
        return "·"
    if r.get("status") == "skipped":
        return "—"
    rel = r.get('rel_to_range', r.get('max_abs_diff', 0))
    if r.get("status") == "ok":
        return f"{rel:.1e}"
    return f"❌{rel:.1e}"
print(f"| {Path('$d').name} | {out_range} | {cell('verify_pt2')} | {cell('verify_onnx')} | {cell('verify_qnn_cpu')} |")
PY
done

mv "$OUT.tmp" "$OUT"
echo "[verify] wrote $OUT"
